// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BooksDocumentDataSlicesSlice =
  | ImageSlice
  | BannerCtaSlice
  | BlockquoteSlice
  | RichTextSlice
  | CalloutBlockSlice;

/**
 * Content for Book documents
 */
interface BooksDocumentData {
  /**
   * Publish Date field in *Book*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: books.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Title field in *Book*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: books.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Sub Title field in *Book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: books.sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Description field in *Book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: books.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *Book*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: books.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<"Card">;

  /**
   * Slice Zone field in *Book*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: books.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BooksDocumentDataSlicesSlice> /**
   * Meta Title field in *Book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: books.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: books.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Book document from Prismic
 *
 * - **API ID**: `books`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BooksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BooksDocumentData>, "books", Lang>;

type BooksArchiveDocumentDataSlicesSlice =
  | BannerCtaSlice
  | SpacerSlice
  | CalloutBlockSlice
  | RichTextSlice;

/**
 * Content for Books Archive documents
 */
interface BooksArchiveDocumentData {
  /**
   * Title field in *Books Archive*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Books
   * - **API ID Path**: books_archive.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Books Archive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: books_archive.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *Books Archive*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: books_archive.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Text Color field in *Books Archive*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: books_archive.text_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_color: prismic.SelectField<"Light" | "Dark", "filled">;

  /**
   * Slice Zone field in *Books Archive*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: books_archive.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BooksArchiveDocumentDataSlicesSlice> /**
   * Meta Title field in *Books Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: books_archive.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Books Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: books_archive.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Books Archive document from Prismic
 *
 * - **API ID**: `books_archive`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BooksArchiveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BooksArchiveDocumentData>,
    "books_archive",
    Lang
  >;

/**
 * Item in *Home Page → Hero Carousel*
 */
export interface HomePageDocumentDataHeroCarouselItem {
  /**
   * Slide Title field in *Home Page → Hero Carousel*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.hero_carousel[].slideTitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slideTitle: prismic.TitleField;

  /**
   * Slide Description field in *Home Page → Hero Carousel*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.hero_carousel[].slideDescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  slideDescription: prismic.RichTextField;

  /**
   * Call-to-action Link field in *Home Page → Hero Carousel*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.hero_carousel[].callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;

  /**
   * Call-to-action Label field in *Home Page → Hero Carousel*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.hero_carousel[].callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * Slide Image field in *Home Page → Hero Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.hero_carousel[].slideImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slideImage: prismic.ImageField<"mobile">;

  /**
   * Slide Style field in *Home Page → Hero Carousel*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Contained
   * - **API ID Path**: home_page.hero_carousel[].slideStyle
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  slideStyle: prismic.SelectField<"Contained" | "Background Image", "filled">;
}

/**
 * Item in *Home Page → Additional News Items*
 */
export interface HomePageDocumentDataAdditionalNewsItemsItem {
  /**
   * Item field in *Home Page → Additional News Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.additional_news_items[].item
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item: prismic.ContentRelationshipField<"books" | "research">;
}

type HomePageDocumentDataSlicesSlice =
  | SpacerSlice
  | SocialCtaSlice
  | RichTextSlice
  | FullWidthCalloutSlice
  | CalloutBlockSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Hero Carousel field in *Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.hero_carousel[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hero_carousel: prismic.GroupField<
    Simplify<HomePageDocumentDataHeroCarouselItem>
  >;

  /**
   * Show Latest News field in *Home Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home_page.show_latest_news
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_latest_news: prismic.BooleanField;

  /**
   * Latest News Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.latest_news_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  latest_news_title: prismic.KeyTextField;

  /**
   * Additional News Items field in *Home Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.additional_news_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  additional_news_items: prismic.GroupField<
    Simplify<HomePageDocumentDataAdditionalNewsItemsItem>
  >;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type NewsDocumentDataSlicesSlice =
  | ImageSlice
  | BannerCtaSlice
  | BlockquoteSlice
  | RichTextSlice
  | CalloutBlockSlice;

/**
 * Content for News documents
 */
interface NewsDocumentData {
  /**
   * Publish Date field in *News*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: news.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Title field in *News*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: news.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<"Card">;

  /**
   * Slice Zone field in *News*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice> /**
   * Meta Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

type NewsArchiveDocumentDataSlicesSlice =
  | BannerCtaSlice
  | SpacerSlice
  | CalloutBlockSlice
  | RichTextSlice;

/**
 * Content for News Archive documents
 */
interface NewsArchiveDocumentData {
  /**
   * Title field in *News Archive*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Books
   * - **API ID Path**: news_archive.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *News Archive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_archive.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *News Archive*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_archive.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Text Color field in *News Archive*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: news_archive.text_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_color: prismic.SelectField<"Light" | "Dark", "filled">;

  /**
   * Slice Zone field in *News Archive*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news_archive.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsArchiveDocumentDataSlicesSlice> /**
   * Meta Title field in *News Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news_archive.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news_archive.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * News Archive document from Prismic
 *
 * - **API ID**: `news_archive`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsArchiveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NewsArchiveDocumentData>,
    "news_archive",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | SpacerSlice
  | CalloutBlockSlice
  | FullWidthCalloutSlice
  | SocialCtaSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Page title...
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Text Colour field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: page.text_colour
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_colour: prismic.SelectField<"Light" | "Dark", "filled">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ResearchDocumentDataSlicesSlice =
  | ImageSlice
  | BannerCtaSlice
  | BlockquoteSlice
  | RichTextSlice
  | CalloutBlockSlice;

/**
 * Content for Research documents
 */
interface ResearchDocumentData {
  /**
   * Title field in *Research*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: research.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Publish Date field in *Research*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: research.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publish_date: prismic.DateField;

  /**
   * Sub Title field in *Research*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: research.sub_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Description field in *Research*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: research.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *Research*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: research.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<"Card">;

  /**
   * Slice Zone field in *Research*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: research.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ResearchDocumentDataSlicesSlice> /**
   * Meta Title field in *Research*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: research.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Research*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: research.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Research document from Prismic
 *
 * - **API ID**: `research`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResearchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResearchDocumentData>,
    "research",
    Lang
  >;

type ResearchArchiveDocumentDataSlicesSlice =
  | BannerCtaSlice
  | SpacerSlice
  | CalloutBlockSlice
  | RichTextSlice;

/**
 * Content for Research Archive documents
 */
interface ResearchArchiveDocumentData {
  /**
   * Title field in *Research Archive*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Books
   * - **API ID Path**: research_archive.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Research Archive*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: research_archive.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Featured Image field in *Research Archive*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: research_archive.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Text Color field in *Research Archive*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: research_archive.text_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_color: prismic.SelectField<"Light" | "Dark", "filled">;

  /**
   * Slice Zone field in *Research Archive*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: research_archive.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ResearchArchiveDocumentDataSlicesSlice> /**
   * Meta Title field in *Research Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: research_archive.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Research Archive*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: research_archive.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * Research Archive document from Prismic
 *
 * - **API ID**: `research_archive`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResearchArchiveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ResearchArchiveDocumentData>,
    "research_archive",
    Lang
  >;

/**
 * Item in *Site Settings → Main Menu*
 */
export interface SiteSettingsDocumentDataMainMenuItem {
  /**
   * Label field in *Site Settings → Main Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.main_menu[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Site Settings → Main Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.main_menu[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Site Settings documents
 */
interface SiteSettingsDocumentData {
  /**
   * Site Name field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.site_name
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_name: prismic.KeyTextField;

  /**
   * Main Menu field in *Site Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.main_menu[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  main_menu: prismic.GroupField<
    Simplify<SiteSettingsDocumentDataMainMenuItem>
  > /**
   * Copyright Text field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.copyright_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  copyright_text: prismic.KeyTextField /**
   * Email address field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.email_address
   * - **Tab**: Contact Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  email_address: prismic.KeyTextField;

  /**
   * Twitter Handle field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.twitter_handle
   * - **Tab**: Contact Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  twitter_handle: prismic.KeyTextField;

  /**
   * Twitter URL field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.twitter_url
   * - **Tab**: Contact Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  twitter_url: prismic.KeyTextField;

  /**
   * Facebook URL field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.facebook_url
   * - **Tab**: Contact Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebook_url: prismic.KeyTextField;

  /**
   * LinkedIn Url field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.linkedin_url
   * - **Tab**: Contact Info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkedin_url: prismic.KeyTextField /**
   * Meta Description field in *Site Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Site Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Site Settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteSettingsDocumentData>,
    "site_settings",
    Lang
  >;

export type AllDocumentTypes =
  | BooksDocument
  | BooksArchiveDocument
  | HomePageDocument
  | NewsDocument
  | NewsArchiveDocument
  | PageDocument
  | ResearchDocument
  | ResearchArchiveDocument
  | SiteSettingsDocument;

/**
 * Primary content in *BannerCta → Primary*
 */
export interface BannerCtaSliceDefaultPrimary {
  /**
   * Text field in *BannerCta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_cta.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * CTA Link field in *BannerCta → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_cta.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * CTA Text field in *BannerCta → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_cta.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;
}

/**
 * Default variation for BannerCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerCta*
 */
type BannerCtaSliceVariation = BannerCtaSliceDefault;

/**
 * BannerCta Shared Slice
 *
 * - **API ID**: `banner_cta`
 * - **Description**: BannerCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerCtaSlice = prismic.SharedSlice<
  "banner_cta",
  BannerCtaSliceVariation
>;

/**
 * Primary content in *Blockquote → Primary*
 */
export interface BlockquoteSliceDefaultPrimary {
  /**
   * Quote text field in *Blockquote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockquote.primary.quote_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote_text: prismic.RichTextField;

  /**
   * Citation field in *Blockquote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockquote.primary.citation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  citation: prismic.KeyTextField;

  /**
   * Fine Print field in *Blockquote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blockquote.primary.fine_print
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fine_print: prismic.KeyTextField;
}

/**
 * Default variation for Blockquote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockquoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlockquoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blockquote*
 */
type BlockquoteSliceVariation = BlockquoteSliceDefault;

/**
 * Blockquote Shared Slice
 *
 * - **API ID**: `blockquote`
 * - **Description**: Blockquote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockquoteSlice = prismic.SharedSlice<
  "blockquote",
  BlockquoteSliceVariation
>;

/**
 * Primary content in *CalloutBlock → Primary*
 */
export interface CalloutBlockSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: callout_block.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile">;

  /**
   * Call-to-action Label field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * Call-to-action Link field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;

  /**
   * Background Colour field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: callout_block.primary.backgroundColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColour: prismic.SelectField<
    | "None"
    | "Primary - Dark"
    | "Primary - Light"
    | "Secondary - Dark"
    | "Secondary - Light"
    | "Grey - Light",
    "filled"
  >;

  /**
   * Full-width? field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: callout_block.primary.fullWidth
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  fullWidth: prismic.BooleanField;
}

/**
 * Default variation for CalloutBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalloutBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CalloutBlock → Primary*
 */
export interface CalloutBlockSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: callout_block.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * image field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile">;

  /**
   * Call-to-action Label field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * Call-to-action Link field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;

  /**
   * Background Colour field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: callout_block.primary.backgroundColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  backgroundColour: prismic.SelectField<
    | "None"
    | "Primary - Dark"
    | "Primary - Light"
    | "Secondary - Dark"
    | "Secondary - Light"
    | "Grey - Light",
    "filled"
  >;

  /**
   * Full-width? field in *CalloutBlock → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: callout_block.primary.fullWidth
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  fullWidth: prismic.BooleanField;
}

/**
 * Image Right variation for CalloutBlock Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutBlockSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<CalloutBlockSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *CalloutBlock*
 */
type CalloutBlockSliceVariation =
  | CalloutBlockSliceDefault
  | CalloutBlockSliceImageRight;

/**
 * CalloutBlock Shared Slice
 *
 * - **API ID**: `callout_block`
 * - **Description**: CalloutBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutBlockSlice = prismic.SharedSlice<
  "callout_block",
  CalloutBlockSliceVariation
>;

/**
 * Primary content in *FullWidthCallout → Primary*
 */
export interface FullWidthCalloutSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: full_width_callout.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile">;

  /**
   * Text Colour field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: full_width_callout.primary.textColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  textColour: prismic.SelectField<"Light" | "Dark", "filled">;

  /**
   * Call-to-action Label field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * Call-to-action Link field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;

  /**
   * Call-to-action Style field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Primary - solid
   * - **API ID Path**: full_width_callout.primary.callToActionStyle
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  callToActionStyle: prismic.SelectField<
    | "Primary - solid"
    | "Primary - outline"
    | "Secondary - solid"
    | "Secondary - outline"
    | "Subtle",
    "filled"
  >;
}

/**
 * Default variation for FullWidthCallout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthCalloutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthCalloutSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *FullWidthCallout → Primary*
 */
export interface FullWidthCalloutSliceImageLeftPrimary {
  /**
   * eyebrowHeadline field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: full_width_callout.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"mobile">;

  /**
   * Text Colour field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Light
   * - **API ID Path**: full_width_callout.primary.textColour
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  textColour: prismic.SelectField<"Light" | "Dark", "filled">;

  /**
   * Call-to-action Label field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.callToActionLabel
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  callToActionLabel: prismic.KeyTextField;

  /**
   * Call-to-action Link field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_callout.primary.callToActionLink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  callToActionLink: prismic.LinkField;

  /**
   * Call-to-action Style field in *FullWidthCallout → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Primary - solid
   * - **API ID Path**: full_width_callout.primary.callToActionStyle
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  callToActionStyle: prismic.SelectField<
    | "Primary - solid"
    | "Primary - outline"
    | "Secondary - solid"
    | "Secondary - outline"
    | "Subtle",
    "filled"
  >;
}

/**
 * Image Left variation for FullWidthCallout Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthCalloutSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<FullWidthCalloutSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *FullWidthCallout*
 */
type FullWidthCalloutSliceVariation =
  | FullWidthCalloutSliceDefault
  | FullWidthCalloutSliceImageLeft;

/**
 * FullWidthCallout Shared Slice
 *
 * - **API ID**: `full_width_callout`
 * - **Description**: FullWidthCallout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthCalloutSlice = prismic.SharedSlice<
  "full_width_callout",
  FullWidthCalloutSliceVariation
>;

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SocialCta → Primary*
 */
export interface SocialCtaSliceDefaultPrimary {
  /**
   * Title field in *SocialCta → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_cta.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for SocialCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialCta*
 */
type SocialCtaSliceVariation = SocialCtaSliceDefault;

/**
 * SocialCta Shared Slice
 *
 * - **API ID**: `social_cta`
 * - **Description**: SocialCta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialCtaSlice = prismic.SharedSlice<
  "social_cta",
  SocialCtaSliceVariation
>;

/**
 * Primary content in *Spacer → Primary*
 */
export interface SpacerSliceDefaultPrimary {
  /**
   * Height field in *Spacer → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Small
   * - **API ID Path**: spacer.primary.height
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  height: prismic.SelectField<"Small" | "Medium" | "Large", "filled">;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpacerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type SpacerSliceVariation = SpacerSliceDefault;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: Spacer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpacerSlice = prismic.SharedSlice<"spacer", SpacerSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BooksDocument,
      BooksDocumentData,
      BooksDocumentDataSlicesSlice,
      BooksArchiveDocument,
      BooksArchiveDocumentData,
      BooksArchiveDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataHeroCarouselItem,
      HomePageDocumentDataAdditionalNewsItemsItem,
      HomePageDocumentDataSlicesSlice,
      NewsDocument,
      NewsDocumentData,
      NewsDocumentDataSlicesSlice,
      NewsArchiveDocument,
      NewsArchiveDocumentData,
      NewsArchiveDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ResearchDocument,
      ResearchDocumentData,
      ResearchDocumentDataSlicesSlice,
      ResearchArchiveDocument,
      ResearchArchiveDocumentData,
      ResearchArchiveDocumentDataSlicesSlice,
      SiteSettingsDocument,
      SiteSettingsDocumentData,
      SiteSettingsDocumentDataMainMenuItem,
      AllDocumentTypes,
      BannerCtaSlice,
      BannerCtaSliceDefaultPrimary,
      BannerCtaSliceVariation,
      BannerCtaSliceDefault,
      BlockquoteSlice,
      BlockquoteSliceDefaultPrimary,
      BlockquoteSliceVariation,
      BlockquoteSliceDefault,
      CalloutBlockSlice,
      CalloutBlockSliceDefaultPrimary,
      CalloutBlockSliceImageRightPrimary,
      CalloutBlockSliceVariation,
      CalloutBlockSliceDefault,
      CalloutBlockSliceImageRight,
      FullWidthCalloutSlice,
      FullWidthCalloutSliceDefaultPrimary,
      FullWidthCalloutSliceImageLeftPrimary,
      FullWidthCalloutSliceVariation,
      FullWidthCalloutSliceDefault,
      FullWidthCalloutSliceImageLeft,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SocialCtaSlice,
      SocialCtaSliceDefaultPrimary,
      SocialCtaSliceVariation,
      SocialCtaSliceDefault,
      SpacerSlice,
      SpacerSliceDefaultPrimary,
      SpacerSliceVariation,
      SpacerSliceDefault,
    };
  }
}
