// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner_cta: dynamic(() => import("./BannerCta")),
  blockquote: dynamic(() => import("./Blockquote")),
  callout_block: dynamic(() => import("./CalloutBlock")),
  full_width_callout: dynamic(() => import("./FullWidthCallout")),
  image: dynamic(() => import("./Image")),
  rich_text: dynamic(() => import("./RichText")),
  social_cta: dynamic(() => import("./SocialCta")),
  spacer: dynamic(() => import("./Spacer")),
};
